server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.107.103.157:3306/ccty?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Zan54321@
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.distance.src.domain.database
  configuration:
    map-underscore-to-camel-case: true
